"""Centralized Transcript Quality Gate for speech validation and hallucination suppression in NOVA Voice V2."""

from __future__ import annotations

import math
import re

from core.logger import get_logger

from voice.state import QualityCheckResult, QualityDecision, TranscriptionResult

logger = get_logger(__name__)

# Common subtitle / closing hallucinations generated by Whisper on non-speech audio (coughs, breaths, room noise)
_COMMON_NOISE_HALLUCINATIONS: frozenset[str] = frozenset({
    "bye thank you",
    "bye thank you.",
    "thank you",
    "thank you.",
    "thank you very much",
    "thank you very much.",
    "thanks for watching",
    "thanks for watching.",
    "thanks for watching!",
    "thank you for watching",
    "thank you for watching.",
    "you",
    "bye",
    "bye.",
    "bye bye",
    "bye bye.",
    "goodbye",
    "goodbye.",
    "subtitles by",
    "subtitles by the amara.org community",
    "translated by",
    "sous-titres",
    "transcription",
    "mbc",
    "silence",
    "applause",
    "laughter",
    "music",
})


class TranscriptQualityGate:
    """Centralized speech acceptance gate evaluating acoustic confidence, lexical structure, and noise artifacts."""

    def __init__(
        self,
        min_confidence: float = 0.50,
        max_no_speech_prob: float = 0.45,
        min_avg_logprob: float = -1.10,
        max_compression_ratio: float = 2.4,
    ) -> None:
        self.min_confidence = min_confidence
        self.max_no_speech_prob = max_no_speech_prob
        self.min_avg_logprob = min_avg_logprob
        self.max_compression_ratio = max_compression_ratio

    def evaluate(self, result: TranscriptionResult) -> QualityCheckResult:
        """Evaluate a TranscriptionResult and return a structured QualityCheckResult.

        Args:
            result: TranscriptionResult from speech transcriber.

        Returns:
            QualityCheckResult containing decision, confidence, and diagnostic reason.
        """
        raw_text = (result.text or "").strip()

        # 1. Empty or whitespace check
        if not raw_text:
            return QualityCheckResult(
                accepted=False,
                decision=QualityDecision.REJECTED_EMPTY,
                confidence=0.0,
                transcript="",
                reason="Empty transcript produced by STT engine.",
                is_command_candidate=False,
            )

        # 2. Text normalization & alphanumeric extraction
        cleaned_words = [re.sub(r"[^\w\s]", "", w).strip() for w in raw_text.lower().split()]
        valid_words = [w for w in cleaned_words if w]
        clean_text = " ".join(valid_words).strip()

        if not valid_words or not clean_text:
            return QualityCheckResult(
                accepted=False,
                decision=QualityDecision.REJECTED_NOISE,
                confidence=0.0,
                transcript=raw_text,
                reason="No alphanumeric words found (audio contained only punctuation or noise markers).",
                is_command_candidate=False,
            )

        # 3. Acoustic metadata thresholds
        no_speech = result.no_speech_prob
        avg_logprob = result.avg_logprob
        comp_ratio = result.compression_ratio
        speech_dur = result.speech_duration or result.duration_seconds

        # Check compression ratio (repetition hallucination loop)
        if comp_ratio > self.max_compression_ratio:
            return QualityCheckResult(
                accepted=False,
                decision=QualityDecision.REJECTED_HALLUCINATION,
                confidence=0.1,
                transcript=raw_text,
                reason=f"High compression ratio ({comp_ratio:.2f} > {self.max_compression_ratio:.2f}) indicates repetitive decoder loop.",
                is_command_candidate=False,
                metadata={"compression_ratio": comp_ratio},
            )

        # Check no-speech probability (coughing, throat clearing, breathing, mic bumps)
        if no_speech > self.max_no_speech_prob:
            return QualityCheckResult(
                accepted=False,
                decision=QualityDecision.REJECTED_NOISE,
                confidence=max(0.0, 1.0 - no_speech),
                transcript=raw_text,
                reason=f"High no-speech probability ({no_speech:.2f} > {self.max_no_speech_prob:.2f}) indicates non-speech acoustic event (e.g. cough, breath, noise).",
                is_command_candidate=False,
                metadata={"no_speech_prob": no_speech},
            )

        # Check acoustic log probability (token confidence)
        if avg_logprob < self.min_avg_logprob and avg_logprob != 0.0:
            return QualityCheckResult(
                accepted=False,
                decision=QualityDecision.REJECTED_NOISE,
                confidence=max(0.0, math.exp(avg_logprob)),
                transcript=raw_text,
                reason=f"Low acoustic log probability ({avg_logprob:.2f} < {self.min_avg_logprob:.2f}) indicates unintelligible acoustic signal.",
                is_command_candidate=False,
                metadata={"avg_logprob": avg_logprob},
            )

        # 4. Lexical Repetition & Entropy Check
        if len(valid_words) >= 4:
            unique_ratio = len(set(valid_words)) / len(valid_words)
            if unique_ratio < 0.35:
                return QualityCheckResult(
                    accepted=False,
                    decision=QualityDecision.REJECTED_HALLUCINATION,
                    confidence=0.15,
                    transcript=raw_text,
                    reason=f"Extreme word repetition (unique ratio {unique_ratio:.2f} < 0.35).",
                    is_command_candidate=False,
                    metadata={"unique_ratio": unique_ratio},
                )

        # 5. Whisper Non-Speech Hallucination Filter
        # Common artifact phrases produced by Whisper when receiving short accidental sounds
        norm_phrase = re.sub(r"[^\w\s]", "", raw_text.lower()).strip()
        if norm_phrase in _COMMON_NOISE_HALLUCINATIONS:
            # If the phrase is a known hallucination token AND confidence is marginal or duration is brief
            if no_speech > 0.20 or (avg_logprob < -0.70 and avg_logprob != 0.0) or (speech_dur > 0 and speech_dur < 0.8):
                return QualityCheckResult(
                    accepted=False,
                    decision=QualityDecision.REJECTED_HALLUCINATION,
                    confidence=0.1,
                    transcript=raw_text,
                    reason=f"Matched non-speech hallucination pattern '{norm_phrase}' with marginal acoustic evidence.",
                    is_command_candidate=False,
                    metadata={"hallucination_pattern": norm_phrase},
                )

        # 6. Confidence Scoring and Acceptance Decision
        effective_confidence = result.confidence
        if effective_confidence <= 0.0 and avg_logprob != 0.0:
            effective_confidence = min(1.0, max(0.0, math.exp(avg_logprob) * (1.0 - no_speech)))

        # Categorize into ACCEPTED vs UNCERTAIN
        if effective_confidence >= self.min_confidence:
            return QualityCheckResult(
                accepted=True,
                decision=QualityDecision.ACCEPTED,
                confidence=effective_confidence,
                transcript=raw_text,
                reason="High speech confidence and valid lexical structure.",
                is_command_candidate=True,
                metadata={
                    "no_speech_prob": no_speech,
                    "avg_logprob": avg_logprob,
                    "compression_ratio": comp_ratio,
                },
            )
        else:
            return QualityCheckResult(
                accepted=True,  # Allow conversational turn, but flagged as uncertain for high-risk actions
                decision=QualityDecision.UNCERTAIN,
                confidence=effective_confidence,
                transcript=raw_text,
                reason=f"Marginal acoustic confidence ({effective_confidence:.2f} < {self.min_confidence:.2f}); flagged as uncertain.",
                is_command_candidate=True,
                metadata={
                    "no_speech_prob": no_speech,
                    "avg_logprob": avg_logprob,
                    "compression_ratio": comp_ratio,
                },
            )
